### PR TITLE
turn off nucleus-electron edges for default ansatz

### PR DESCRIPTION
**Pull request by szbernat**
Use `positional_electron_embeddings=true` instead.

### CODE REVIEW

**Review by zenoone — COMMENTED** [review]
What about removing the `ne` `edge_types`?

**Comment by szbernat** [comment]
Removed `ne` from `edge_types` too.

**Comment by zenoone** [comment]
And I guess the tests also have to be updated :upside_down_face: .

**Comment by szbernat** [comment]
The tests run with their own config files which weren't changed, right? Or do you mean to remove `ne` from those configs too?

**Review by zenoone — APPROVED** [review]

**Comment by zenoone** [comment]
Yeah, I saw that too. I guess its fine to keep it as is.

**Pull request merged**
